name: randomize_photo_mosh
description: Outputs random image modifications to a provided image using photo-mosh.

version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  puppeteer: ^2.12.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
